{% set name = "pystac" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystac-{{ version }}.tar.gz
  sha256: 6ec43e1c6bec50fbfbdede49c3ccb83ecd112072a938001b5c9c581fc2945e83

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil >=2.7.0

test:
  imports:
    - pystac
    - pystac.extensions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/azavea/pystac.git
  summary: Python library for working with Spatiotemporal Asset Catalog (STAC).
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
