{% set version = "0.3.4" %}


package:
  name: pystac
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pystac/pystac-{{ version }}.tar.gz
  sha256: acee95447f3c6d4a2d4597160a6cf7e050f6b0961a440e1f7f2e8725c27cf626

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil >=2.7.0

test:
  imports:
    - pystac
    - pystac.serialization
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pystac/
  summary: Python library for working with Spatiotemporal Asset Catalog (STAC).
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
